# Generated by Django 4.0.6 on 2022-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
