# Generated by Django 4.0.6 on 2022-07-27 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_deposithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposithistory',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 7, 31, 245805)),
        ),
    ]
