# Generated by Django 4.0.6 on 2022-07-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_deposit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposithistory',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_history', to='payment.deposit'),
        ),
    ]
