# Generated by Django 4.0.6 on 2022-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('country_user', 'Country User'), ('local_user', 'Local User')], max_length=20),
        ),
    ]
