# Generated by Django 4.0.6 on 2022-07-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_agent_type_alter_agent_country_and_more'),
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
            preserve_default=False,
        ),
    ]
