# Generated by Django 4.0.6 on 2022-07-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agent',
        ),
    ]
