# Generated by Django 4.0.6 on 2022-07-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0006_alter_agent_email_alter_agent_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_name', models.FileField(upload_to='ok')),
            ],
        ),
        migrations.CreateModel(
            name='MarkupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('hotel', 'Hotel'), ('air', 'Air')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('markup_amount', models.IntegerField()),
                ('markup_type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('applicable_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
            ],
        ),
    ]
