# Generated by Django 4.0.6 on 2022-07-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_agent_email_alter_agent_phone_number_and_more'),
        ('settings', '0002_remove_fileupload_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('uk', 'UK'), ('bd', 'BD'), ('ind', 'IND'), ('mal', 'MAL'), ('pk', 'PK'), ('sf', 'SF'), ('usa', 'USA'), ('aus', 'AUS')], max_length=20)),
                ('rate', models.IntegerField()),
                ('applicable_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='markupsetting',
            unique_together={('name', 'applicable_for')},
        ),
        migrations.CreateModel(
            name='CurrencySettingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('uk', 'UK'), ('bd', 'BD'), ('ind', 'IND'), ('mal', 'MAL'), ('pk', 'PK'), ('sf', 'SF'), ('usa', 'USA'), ('aus', 'AUS')], max_length=20)),
                ('current_rate', models.IntegerField()),
                ('current_start_date', models.DateTimeField()),
                ('previous_rate', models.IntegerField(blank=True, null=True)),
                ('previous_start_date', models.DateTimeField(blank=True, null=True)),
                ('currency_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.currencysetting')),
            ],
        ),
    ]
