# Generated by Django 4.0.6 on 2022-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('currency', models.CharField(max_length=70)),
                ('unique_identifier', models.CharField(max_length=70)),
                ('payment_policy', models.CharField(max_length=70)),
            ],
        ),
    ]
