# Generated by Django 4.0.6 on 2022-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('country_agent', 'Country Agent'), ('local_agent', 'Local Agent')], default='country_agent', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='country',
            field=models.CharField(choices=[('uk', 'UK'), ('bd', 'BD'), ('ind', 'IND'), ('mal', 'MAL'), ('pk', 'PK'), ('sf', 'SF'), ('usa', 'USA'), ('aus', 'AUS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='payment_policy',
            field=models.CharField(choices=[('credit', 'Credit'), ('prepaid', 'Prepaid')], max_length=20),
        ),
    ]
