# Generated by Django 4.0.6 on 2022-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_agent_type_alter_agent_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
