# Generated by Django 4.0.6 on 2022-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agent_signup_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='balance',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
