# Generated by Django 4.0.6 on 2022-07-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agent_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
