# Generated by Django 4.0.6 on 2022-07-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_agent_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='unique_identifier',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
